### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by parulagrawal14** [sunwxg/decode_by_libwireshark#1]
Hello,
# I am getting below mentioned errors while compiling the code:

In file included from frame_tvbuff.c:31:0:
./include/frame_tvbuff.h:34:64: error: unknown type name ‘Buffer’
 extern tvbuff_t *frame_tvbuff_new_buffer(const frame_data *fd, Buffer *buf);
                                                                ^
./include/frame_tvbuff.h:38:63: error: unknown type name ‘Buffer’
 extern tvbuff_t *file_tvbuff_new_buffer(const frame_data *fd, Buffer *buf);
                                                               ^
In file included from ./include/globals.h:26:0,
                 from frame_tvbuff.c:32:
./include/file.h:30:24: fatal error: epan/print.h: No such file or directory
 #include <epan/print.h>
                        ^
compilation terminated.
myshark.c:10:34: fatal error: wireshark/epan/print.h: No such file or directory
 #include <wireshark/epan/print.h>
                                  ^
compilation terminated.
# make: **\* [default] Error 1

Machine configuration used:
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

Can you provide me the steps  to resolve the above issue.

Thanks

**Comment by sunwxg** [comment]
Have you installed:

```
sudo apt-get install libwireshark-dev libglib2.0-dev libwiretap-dev
```

Do you have file /usr/include/wireshark/epan/print.h ?

```
find /usr/include -name "print.h"
```

**Comment by sunwxg** [comment]
I have updated repo, please update your source and make again following README.

```
git pull
cat libs/libwireshark.{00,01,02,03} > libs/libwireshark.so
chmod 775 libs/libwireshark.so
```

**Comment by parulagrawal14** [comment]
Hi,

Thank you  very much.
Compilation is successful with the updated repo.

Thanks and Regards,
Parul
