### ISSUE TITLE
running time error- Segmentaion fault on epan_init

### ISSUE THREAD

**Issue by JakeAbo** [sunwxg/decode_by_libwireshark#10]
Hey,

I try to run your code but program crash on epan_init function. i get the following running time error:

> 

    Enter file name: 1.pcap

    Enter print type(0-XML, 1-TEXT): 1

    Init function start

    Segmentaion fault (core dumped)

    Process returned 139 (0x8B) execution time : 2.882 s

    Press ENTER to continue.

Source code : https://stackoverflow.com/questions/46263024/getting-segmentaion-fault-in-c-ubuntu-when-trying-to-run-function-from-so-libar

**Comment by sunwxg** [comment]
My code only work on wireshark version 1.12.8, it can't work on newest wireshark version.

You can use 'so' file in my source code package, it should work.

**Comment by JakeAbo** [comment]
I am using your .so libs. Still get the same error... should i use the same include files too?

**Comment by sunwxg** [comment]
Yes, use include files in my package.

**Comment by JakeAbo** [comment]
Same error... Any other ideas?

**Comment by sunwxg** [comment]
CFLAGS+= -I./include/wireshark
CFLAGS+= -I./include/wireshark/wiretap
CFLAGS+= -I./include
LDFLAGS= -L./libs -lwiretap -lwireshark -lwsutil -lglib-2.0
LDFLAGS+= -Wl,-rpath,./libs

You should use these compiling flags, that let you use my include files and .so file

**Comment by sunwxg** [comment]
First you can try my code.

Go to my code folder, then do command 'make'. What is result?

**Comment by sunwxg** [comment]
Your code work for me.

> Enter file name: 1.pcap
> Enter print type(0-XML, 1-TEXT): 1
> Init function start
> Init proccesss politices done
> 
> 
> 1.pcap

Copy your .c file into my code foder as test.c
Add item in Makefile file

```
diff --git a/Makefile b/Makefile
index 75603b0..4d1e7ec 100755
--- a/Makefile
+++ b/Makefile
@@ -14,6 +14,8 @@ SRC_WIRESHARK?=~/person/wireshark-1.12.8
 default:
        @gcc ${CFLAGS} -o ${TARGET} ${SRC} ${LDFLAGS}
 
+test: test.c
+
 debug:
        @libtool --silent --tag=CC --mode=link \
        gcc ${CFLAGS} ${INCLUDE} -o ${TARGET} ${SRC} \
```
Then do command 'make test'.

**Comment by JakeAbo** [comment]
I used higher version of libwireshark, libwsutil and libwiretap and its work fine for me now.
thanks anyway!
