### ISSUE TITLE
needs too long time to decode big file 

### ISSUE THREAD

**Issue by qchai** [sunwxg/decode_by_libwireshark#2]
Hi,
    when I run decode_by_libwireshark to decode a pcap file(about 400M), It takes a long time to decode it,all finished more than 20 minutes. When I open the same file user wireshark, it takes a few seconds.I don't know  why decode_by_libwireshark takes so long time,  do you have any idea?

**Comment by sunwxg** [comment]
For my understanding, when wireshark open file, it only decode part of file, not all the file. 
You can try tshark to decode your file, I think it should be almost same time with decode_by_libwireshark.

**Comment by qchai** [comment]
Use tshark to decode my file also takes so long time.
Thank you very much.
