### ISSUE TITLE
你好,我现在在做一个关于调用libwireshark.so的项目，想咨询你点问题，可以加个qq帮助一下我么，qq1264720607，谢谢

### ISSUE THREAD

**Issue by leguandemomotou** [sunwxg/decode_by_libwireshark#3]
你好,我现在在做一个关于调用libwireshark.so的项目，想咨询你点问题，可以加个qq帮助一下我么，qq1264720607，谢谢

**Comment by leguandemomotou** [comment]
你好,我现在在做一个关于调用libwireshark.so的项目，想咨询你点问题，可以加个qq帮助一下我么，qq1264720607，谢谢

**Comment by sunwxg** [comment]
先发邮件说一些大概情况吧，我看看能否帮到你。
