### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by leguandemomotou** [sunwxg/decode_by_libwireshark#5]
[xiaotao@localhost decode_by_libwireshark]$ make
./libs/libwiretap.so: undefined reference to `memcpy@GLIBC_2.14'
collect2: ld 返回 1
make: *** [default] 错误 1

我直接考过去错误如下，应该是glib版本问题

**Comment by sunwxg** [comment]
应该是centos上的glib版本比较低造成的。
