### ISSUE TITLE
感谢

### ISSUE THREAD

**Issue by leguandemomotou** [sunwxg/decode_by_libwireshark#8]
非常感谢你的帮助，我在centos上成功调试了，是glib版本的问题，非常感谢，另外请教下，你当时是怎么确定调用动态库时的需要用到哪些函数和哪些动态库的呢，非常感谢

**Comment by sunwxg** [comment]
你从wireshark源码编译一下，就知道需要那些依赖了。wireshark编译说明里面应该有。
